src/apps/blog/urls.py
from django.urls import path

from .views import PornoStarList, PornoStarShareView, DetailView

app_name = 'star'

urlpatterns = [
    path('', PornoStarList.as_view(), name="star_list"),
    path('<slug:tag_slug>', PornoStarList.as_view(), name="star_list_by_tag"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>', DetailView.as_view(),
         name="star_detail"),
    path('share/<slug:slug>', PornoStarShareView.as_view(), name="star_share"),
]

src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += [
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    import socket  # only if you haven't already imported this

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    allowed_ips = ["127.0.0.1", "10.0.2.2"]
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + allowed_ips

src/apps/blog/models/comment.py
from django.db import models

from .porno_star import PornoStar


class CustomManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Comment.Status.PUBLISHED)


class CommentUser(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()

    def __str__(self) -> str:
        return f"{self.name}"


class Comment(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        FIXING = 'FX', 'Fixing'
        PUBLISHED = 'PB', 'Publish'

    pornostar = models.ForeignKey(PornoStar, on_delete=models.CASCADE,
                                  related_name="comments")
    comment_user = models.OneToOneField(CommentUser, on_delete=models.CASCADE,
                                        related_name='comment')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.PUBLISHED)

    objects = models.Manager()
    published = CustomManager()

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self) -> str:
        return f"Comment written by {self.comment_user.name} " \
               f"on {self.pornostar.name}"

src/apps/blog/models/porno_star.py
from typing import cast

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone

from lorem import get_word
from taggit.managers import TaggableManager

User = get_user_model()


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=PornoStar.Status.PUBLISHED)


class PornoStar(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    name = models.CharField(max_length=64)
    slug = models.SlugField(unique_for_date='publish')
    content = models.TextField(default=get_word(count=100).capitalize())
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, related_name='pornostars',
                               on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='star/%Y/%m/%d/', null=True)
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishManager()

    class Meta:
        verbose_name = 'Pornostar'
        verbose_name_plural = 'Pornostars'
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['publish'])
        ]

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        pb = cast(timezone.now, self.publish)
        return reverse('blog:star_detail',
                       args=[pb.year, pb.month, pb.day, self.slug])

src/apps/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from taggit.forms import TagField

from .models import Comment, CommentUser, PornoStar


class SharePornoStarForm(forms.Form):
    name = forms.CharField(
        max_length=64, widget=forms.TextInput(attrs={"placeholder": "Name"})
    )
    email_to = forms.EmailField(
        widget=forms.TextInput(attrs={"placeholder": "Email to"})
    )
    content = forms.CharField(widget=forms.Textarea)


class CommentUserForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Name"})
    )
    email = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Email"})
    )

    class Meta:
        model = CommentUser
        fields = ('name', 'email')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


def clean_tags(*args):
    args = args[0].split(',')
    if len(args) > 5:
        raise ValidationError(
            message='Tags amount must be more than 5',
            code='invalid',
        )


class PornoStarAdminForm(forms.ModelForm):
    tags = TagField(validators=[clean_tags])

    class Meta:
        model = PornoStar
        fields = '__all__'

src/apps/blog/views/pornostar_detail.py
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import QuerySet, Count, Subquery
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import View

from apps.blog.forms import CommentForm, CommentUserForm
from apps.blog.models import PornoStar, Comment


class StarCommentsGetterMixin:
    @staticmethod
    def get_queries(year: int, month: int, day: int,
                    slug: str) -> tuple[QuerySet, ...]:
        """
        Realize queries such as ( star, comments, recommendations ).
        RETURNS:
            star, comments, recommendations.
        """
        star = get_object_or_404(
            PornoStar.published.select_related('author')
            .only('name', 'slug', 'content', 'publish', 'image',
                  'author__username', 'tags__name'),
            slug=slug, publish__year=year,
            publish__month=month, publish__day=day
        )
        comments = Comment.published.filter(pornostar_id=star.id) \
            .select_related('comment_user') \
            .only('comment_user__name', 'content', 'created')

        recommendations = PornoStar.published.filter(
            tags__in=Subquery(star.tags.values_list('id', flat=True))
        ).exclude(pk=star.pk).alias(same_tags=Count('tags'))\
            .order_by('-same_tags', 'publish')\
            .only('name', 'content', 'image', 'slug', 'publish')[:7]

        return star, comments, recommendations


class DetailView(StarCommentsGetterMixin, View):
    template_name: str = 'blog/detail.html'

    def get(self, request: WSGIRequest, year: int, month: int,
            day: int, slug: str) -> HttpResponse:
        """
        Get star, comments, recommendations.
        RENDERS:
            star, comments, recommendations, clear forms.
        """
        queries = self.get_queries(year, month, day, slug)
        star, comments, recommendations = queries

        comment_user_form = CommentUserForm()
        comment_form = CommentForm()

        context = {
            'star': star,
            'comments': comments,
            'recommendations': recommendations,
            'comment_user_form': comment_user_form,
            'comment_form': comment_form,
        }

        return render(request, self.template_name, context)

    def post(self, request: WSGIRequest, year: int, month: int,
             day: int, slug: str) -> HttpResponse:
        """
        Get star, comments, recommendations and validate form data.
        RENDERS:
            star, comments, recommendations,
            clear or complete forms,
            open_comment_form = True - always open form.
        """
        queries = self.get_queries(year, month, day, slug)
        star, comments, recommendations = queries

        post = request.POST
        comment_user_form = CommentUserForm(data={
            'name': post.get('name'),
            'email': post.get('email')
        })
        comment_form = CommentForm({'content': post.get('content')})

        if comment_user_form.is_valid() and comment_form.is_valid():
            comment_form = comment_form.save(commit=False)
            comment_form.pornostar = star
            comment_form.comment_user = comment_user_form.save()
            comment_form.save()

            comment_user_form = CommentUserForm()
            comment_form = CommentForm()

        context = {
            'star': star,
            'comments': comments,
            'recommendations': recommendations,
            'comment_user_form': comment_user_form,
            'comment_form': comment_form,
            'open_comment_form': True,
        }

        return render(request, self.template_name, context)

src/apps/blog/views/pornostar_list.py
import copy

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Prefetch
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from taggit.models import Tag

from apps.blog.models import PornoStar


class PornoStarList(View):
    paginate_by = 7
    template_name = 'blog/list.html'

    def get(self, request, tag_slug=None) -> HttpResponse:
        """
        Get pagination using star.
        Get and Pop email, star_name from session.
        RENDERS:
            title, pagination.
        """
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            pornostars = PornoStar.published.filter(tags__in=[tag])
        else:
            pornostars = PornoStar.published.all()

        pornostars = pornostars.prefetch_related(
            Prefetch('tags')
        ).only('name', 'slug', 'content', 'image', 'publish')

        paginator = Paginator(pornostars, self.paginate_by)
        page_number = request.GET.get('page', 1)

        try:
            pornostars_per_page = paginator.page(page_number)
        except EmptyPage:
            pornostars_per_page = paginator.page(paginator.num_pages)
        except PageNotAnInteger:
            pornostars_per_page = paginator.page(1)

        context = {'title': 'PornoStars', 'pornostars': pornostars_per_page}

        if share_data := request.session.get("share_success_data"):
            context.setdefault('email_to', copy.copy(share_data['email_to']))
            context.setdefault('star_name', copy.copy(share_data['star_name']))
            request.session.pop('share_success_data')

        return render(request, self.template_name, context)

src/apps/blog/views/pornostar_share.py
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from apps.blog.forms import SharePornoStarForm
from apps.blog.models import PornoStar


class PornoStarShareView(View):
    template_name = 'blog/share.html'

    def get(self, request, slug: str) -> HttpResponse:
        """
        Get star, clear form.
        RENDERS:
            star, clear form.
        """
        star = get_object_or_404(PornoStar.published, slug=slug)
        form = SharePornoStarForm()
        context = {'star': star, 'form': form}
        return render(request, self.template_name, context)

    def post(self, request, slug: str) -> HttpResponse:
        """
        Get star, send mail, create session data( email_to, star_name ).
        IF FROM VALID:
            REDIRECT to list.html with session data.
        RENDERS:
            star, complete form.
        """
        star = get_object_or_404(PornoStar.published, slug=slug)

        if (form := SharePornoStarForm(request.POST)).is_valid():
            cd = form.cleaned_data

            # send message to email
            absolute_url = request.build_absolute_uri(star.get_absolute_url())
            subject = f"{cd['name']} recommends looking at {star.name}"
            message = f"Look at {cd['name']} at {absolute_url}\n\n" \
                      f"{cd['name']}'s message: {cd['text']}"
            email_from = settings.EMAIL_HOST_USER
            send_mail(subject, message, email_from, [cd['email_to']])

            # save email and star_name to session and redirect tolist.html page
            request.session['share_success_data'] = {
                'email_to': cd["email_to"],
                'star_name': star.name,
            }
            return redirect(reverse('blog:star_list'))

        context = {'star': star, 'form': form}
        return render(request, self.template_name, context)

src/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ star.name }}{% endblock %}

{% block head %}
    {% load truncate_line_filter %}
    {% load humanize %}
    {% load static %}
    <link href="{% static 'css/blog/detail_star.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog/share_form.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog/comment.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog/comment_form.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog/recommendations.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="detail_star">
        <div class="detail_star__star">
            <div class="detail_star__image">
                <div class="detail_image_wrapper">
                    <img class="detail_star__img" src="{{ star.image.url }}"
                         ondragstart="return false" alt="no image">
                    <div class="command_sidebar">
                        <div class="command_sidebar__container">
                            <a href="{% url 'blog:star_share' star.slug %}" class="share_form_link">
                                Share this star
                            </a>
                            <p class="comment_form_link">
                                Add comment
                            </p>
                        </div>
                    </div>
                    <div class="recommendations">
                        <div class="recommendations__title">Recommended</div>
                        <div class="recommendations__content">
                            {% for recommendation in recommendations %}
                                <div class="recommendation_item">
                                    {% with recommendation_url=recommendation.get_absolute_url %}
                                        <div class="recommendation_item__container">
                                            <div class="recommendation_item__img">
                                                <a href="{{ recommendation_url }}">
                                                    <img src="{{ recommendation.image.url }}"
                                                         ondragstart="return false"alt="no image">
                                                </a>
                                            </div>
                                            <div class="right_card_part">
                                                <div class="recommendation_item__name">
                                                    <a href="{{ recommendation_url }}">
                                                        {{ recommendation.name }}
                                                    </a>
                                                </div>
                                                <div class="recommendation_item__content">
                                                    <a href="{{ recommendation_url }}">
                                                        {{ recommendation.content | truncatechars:"20" }}
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    {% endwith %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <p class="detail_star__name">{{ star.name }}</p>
            <p class="detail_star__content">{{ star.content }}</p>
            <div class="add_info">
                Created <p class="detail_star__publish">{{ star.publish  }}</p>
                By <p class="detail_star__author">{{ star.author.username }}</p>
            </div>
        </div>
        <br />
        <div class="comments">
            <div class="comments__container">
                <p class="comments__title">Comments</p>
                <div class="button_add_comment" id="id_comment_form">
                    <span class="button_add_comment__content">Add comment</span>
                </div>
            </div>

            <div class="blank"></div>

            {% include 'blog/include/comment_form.html' %}

             <div class="comment_items">
                {% for comment in comments %}
                    <div class="comment_item">
                        <img class="user_icon" src="{% static 'images/blog/user_icon.png' %}" />
                        <div class="comment_item__info">
                            <span class="comment_item__username">{{ comment.comment_user.name }}</span>
                            <span class="comment_item__publish">
                                {{ comment.created | naturaltime }}
                            </span>
                            {% with comment_content=comment.content %}
                                <div class="comment_item__content">
                                    {{ comment_content | truncate_line }}
                                </div>
                                <div class="comment_item__full_content no_display">
                                    {{ comment.content | truncate_line:'"100","63","None","comment_messages"' }}
                                    <p class="comment_message_less">Show less</p>
                                </div>
                            {% endwith %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {% if not comments.exists %}
        <script type="text/javascript" src="{% static 'js/blog/add_inner_html_to_blank.js' %}"></script>
    {% endif %}

    <script src="{% static 'js/blog/comment_form_drag.js' %}" type="text/javascript"></script>

    {% if open_comment_form %}
        <script type="text/javascript">comment_form.classList.remove("no_display")</script>
    {% endif %}

    <script src="{% static 'js/blog/comment_read_more.js' %}" type="text/javascript"></script>
{% endblock %}

src/templates/blog/list.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block head %}
    {% load static %}
    <link href="{% static 'css/blog/stars.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog/tags.css' %}" rel="stylesheet" />
{% endblock %}

{% block share_success %}
    <!---->
    {% if star_name and email_to %}
        <div id="share_success">
            {{ star_name }} was successfully sent to: {{ email_to }}
            <span class="cross noselect">&#215;</span>
        </div>
    {% endif %}
    <!---->
{% endblock %}

{% block content %}
<div class="stars_container">
    <div class="stars">
        {% for star in pornostars %}
            <div class="star">
                <div class="star__item">
                    {% if star.image %}
                        <img onclick='location.href="{{ star.get_absolute_url }}"'
                             class="micro_star_img" src="{{ star.image.url }}" alt="no image" />
                    {% endif %}
                    <div class="star__content__container">
                        <h2 onclick='location.href="{{ star.get_absolute_url }}"'
                            class="star__name">{{ star.name }}</h2>
                        <p onclick='location.href="{{ star.get_absolute_url }}"'
                           class="star__content">{{ star.content | truncatechars:80 }}</p>
                        <div class="tags">
                            {% for tag in star.tags.all %}
                                <div class="tag_item">
                                    <a href="{% url 'star:star_list_by_tag' tag.slug %}">
                                        {{ tag.name }}
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p class="stars__empty_message">No stars yet</p>
        {% endfor %}
    </div>
    {% include 'include/pagination.html' with page=pornostars %}
</div>
{% endblock %}

{% block script %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/blog/base.js' %}"></script>
{% endblock %}

src/templates/blog/share.html
{% extends 'base.html' %}

{% block title %}Share {{ star.name }}{% endblock %}

{% block head %}
{% load static %}
    <link href="{% static 'css/blog/share_form.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="share_form">
        <form action="{% url 'blog:star_share' star.slug %}" method="POST">
            <div class="share_headline">Share {{ star.name }}</div>
            {% for field in form %}
                <div class="share_from__field">
                    {{ field.errors }}
                    {{ field }}
                </div>
                <br />
            {% endfor %}
            <button type="submit" value="submit">send</button>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}