src/apps/blog/urls.py
from django.urls import path

from .views import PornoStarList, PornoStarShareView, DetailView

app_name = 'star'

urlpatterns = [
    path('', PornoStarList.as_view(), name="star_list"),
    path('<slug:tag_slug>', PornoStarList.as_view(), name="star_list_by_tag"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>', DetailView.as_view(),
         name="star_detail"),
    path('share/<slug:slug>', PornoStarShareView.as_view(), name="star_share"),
]

src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += [
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    import socket  # only if you haven't already imported this

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    allowed_ips = ["127.0.0.1", "10.0.2.2"]
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + allowed_ips

src/templates/include/footer.html
<p class="footer__text">Created by Vlad Zamatevski</p>

src/templates/include/header.html
<a class="header__button" href="{% url 'blog:star_list' %}">
    <h1>Home</h1>
</a>

src/templates/include/pagination.html
<div class="pagination">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</div>